apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpq6rk4m8-nodejs
  janus-idp.io/tekton: hpq6rk4m8-nodejs
  backstage.io/kubernetes-id: hpq6rk4m8-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hpq6rk4m8-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
